#!/bin/bash

exists() {
	type $1 >/dev/null 2>/dev/null
	return $?
}

wayland=`loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'`
if [[ $wayland = wayland ]] ; then
	exists fuzzel && dmenu="fuzzel -d"
else
	exists rofi && dmenu="rofi -dmenu"
	exists dmenu && dmenu="dmenu"
fi

[[ -z $dmenu ]] && echo "No dmenu-like program is installed. Install dmenu or rofi for X, fuzzel for wayland" >&2 && exit 1

opener=xdg-open
type $opener >/dev/null || opener=surf

WIKI_PATH=/usr/share/doc/arch-wiki/html/en

WIKI_SEARCH=$(find "$WIKI_PATH" -maxdepth 1 -type f -name '*.html' | sed -E 's|.*/||; s/\.html$//; s/_/ /g' | uniq | sort | $dmenu "$@" | sed 's/ /_/g')
WIKI="$WIKI_PATH/$WIKI_SEARCH.html"

[ ! -f "$WIKI" ] && echo "No item named ${WIKI_SEARCH} was found." >&2 && exit 1

$opener $WIKI
